import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../core/theme/app_theme.dart';

/// Reports screen with tabs: Incidents, PPE Compliance, Risk Trend
class ReportsListScreen extends StatefulWidget {
  const ReportsListScreen({super.key});

  @override
  State<ReportsListScreen> createState() => _ReportsListScreenState();
}

class _ReportsListScreenState extends State<ReportsListScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  String _selectedSite = 'Site A';
  String _selectedPeriod = 'Last 30 Days';

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _generatePdf() async {
    final pdf = pw.Document();

    // Load a font
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'SafeSite AI Report',
                      style: pw.TextStyle(font: fontBold, fontSize: 24),
                    ),
                    pw.Text(
                      DateTime.now().toString().split(' ')[0],
                      style: pw.TextStyle(font: font, fontSize: 12),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                'Site: $_selectedSite',
                style: pw.TextStyle(font: font, fontSize: 14),
              ),
              pw.Text(
                'Period: $_selectedPeriod',
                style: pw.TextStyle(font: font, fontSize: 14),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                'Executive Summary',
                style: pw.TextStyle(font: fontBold, fontSize: 16),
              ),
              pw.SizedBox(height: 10),
              pw.Text(
                'During the last 30 days, 5 incidents were reported on $_selectedSite. '
                'One incident was classified as High Severity. Immediate action is recommended.',
                style: pw.TextStyle(font: font, fontSize: 12),
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _buildPdfStatCard(
                    font,
                    fontBold,
                    'Total Incidents',
                    '5',
                    PdfColors.black,
                  ),
                  _buildPdfStatCard(
                    font,
                    fontBold,
                    'High Severity',
                    '1',
                    PdfColors.red,
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                'Incident List',
                style: pw.TextStyle(font: fontBold, fontSize: 16),
              ),
              pw.SizedBox(height: 10),
              _buildPdfIncidentItem(
                font,
                fontBold,
                'Near Miss: Fall Hazard',
                'Oct 23, 2023',
                PdfColors.red,
              ),
              _buildPdfIncidentItem(
                font,
                fontBold,
                'Equipment Malfunction',
                'Oct 21, 2023',
                PdfColors.orange,
              ),
              _buildPdfIncidentItem(
                font,
                fontBold,
                'Minor Injury: Cut',
                'Oct 19, 2023',
                PdfColors.orange,
              ),
              _buildPdfIncidentItem(
                font,
                fontBold,
                'Property Damage',
                'Oct 15, 2023',
                PdfColors.grey,
              ),
              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text(
                  'Generated by SafeSite AI',
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    // Save/Print the PDF
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  pw.Widget _buildPdfStatCard(
    pw.Font font,
    pw.Font fontBold,
    String label,
    String value,
    PdfColor color,
  ) {
    return pw.Container(
      width: 200,
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              font: font,
              fontSize: 12,
              color: PdfColors.grey700,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            value,
            style: pw.TextStyle(font: fontBold, fontSize: 24, color: color),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildPdfIncidentItem(
    pw.Font font,
    pw.Font fontBold,
    String title,
    String date,
    PdfColor color,
  ) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Row(
            children: [
              pw.Container(
                width: 10,
                height: 10,
                decoration: pw.BoxDecoration(
                  color: color,
                  shape: pw.BoxShape.circle,
                ),
              ),
              pw.SizedBox(width: 10),
              pw.Text(title, style: pw.TextStyle(font: fontBold, fontSize: 12)),
            ],
          ),
          pw.Text(
            date,
            style: pw.TextStyle(
              font: font,
              fontSize: 12,
              color: PdfColors.grey700,
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundLight,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.menu, color: AppColors.textLightPrimary),
          onPressed: () => context.go('/dashboard'),
        ),
        title: Text(
          'Reports',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: AppColors.textLightPrimary,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(
              Icons.account_circle_outlined,
              color: AppColors.textLightPrimary,
            ),
            onPressed: () {},
          ),
        ],
      ),
      body: Column(
        children: [
          // Site Filter Chips
          Container(
            color: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: Row(
              children: [
                _buildSiteChip('Site A', _selectedSite == 'Site A'),
                const SizedBox(width: 8),
                _buildSiteChip('Site B', _selectedSite == 'Site B'),
                const SizedBox(width: 8),
                _buildSiteChip('All Sites', _selectedSite == 'All Sites'),
              ],
            ),
          ),
          // Period Selector
          Container(
            color: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: Row(
              children: [
                PopupMenuButton<String>(
                  initialValue: _selectedPeriod,
                  onSelected: (String value) {
                    setState(() {
                      _selectedPeriod = value;
                    });
                  },
                  itemBuilder: (BuildContext context) =>
                      <PopupMenuEntry<String>>[
                        const PopupMenuItem<String>(
                          value: 'Today',
                          child: Text('Today'),
                        ),
                        const PopupMenuItem<String>(
                          value: 'Yesterday',
                          child: Text('Yesterday'),
                        ),
                        const PopupMenuItem<String>(
                          value: 'Last 7 Days',
                          child: Text('Last 7 Days'),
                        ),
                        const PopupMenuItem<String>(
                          value: 'Last 30 Days',
                          child: Text('Last 30 Days'),
                        ),
                      ],
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 8,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.grey.shade100,
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.calendar_today,
                          size: 16,
                          color: AppColors.textLightPrimary,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          _selectedPeriod,
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                            color: AppColors.textLightPrimary,
                          ),
                        ),
                        const SizedBox(width: 4),
                        Icon(
                          Icons.arrow_drop_down,
                          color: AppColors.textLightPrimary,
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
          // Tab Bar
          Container(
            color: Colors.white,
            child: TabBar(
              controller: _tabController,
              labelColor: const Color(0xFF3B82F6),
              unselectedLabelColor: AppColors.textLightSecondary,
              indicatorColor: const Color(0xFF3B82F6),
              labelStyle: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
              tabs: const [
                Tab(text: 'Incidents'),
                Tab(text: 'PPE Compliance'),
                Tab(text: 'Risk Trend'),
              ],
            ),
          ),
          // Tab Content
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: [
                _buildIncidentsTab(),
                _buildPPEComplianceTab(),
                _buildRiskTrendTab(),
              ],
            ),
          ),
          // Export Buttons
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.white,
            child: Row(
              children: [
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: _generatePdf,
                    icon: const Icon(Icons.picture_as_pdf),
                    label: const Text('Export PDF'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF3B82F6),
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSiteChip(String label, bool isSelected) {
    return GestureDetector(
      onTap: () {
        setState(() {
          _selectedSite = label;
        });
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
          color: isSelected ? const Color(0xFF3B82F6) : Colors.grey.shade100,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w500,
            color: isSelected ? Colors.white : AppColors.textLightPrimary,
          ),
        ),
      ),
    );
  }

  Widget _buildIncidentsTab() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          // Stats Cards
          Row(
            children: [
              Expanded(
                child: _buildStatCard('Total Incidents', '5', Colors.black),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildStatCard('High Severity', '1', AppColors.riskHigh),
              ),
            ],
          ),
          const SizedBox(height: 16),
          // Incident List
          _buildIncidentItem(
            icon: Icons.cancel_outlined,
            iconColor: AppColors.riskHigh,
            title: 'Near Miss: Fall Hazard',
            date: 'Oct 23, 2023 - Site A',
          ),
          _buildIncidentItem(
            icon: Icons.warning_amber,
            iconColor: AppColors.riskMedium,
            title: 'Equipment Malfunction',
            date: 'Oct 21, 2023 - Site A',
          ),
          _buildIncidentItem(
            icon: Icons.warning_amber,
            iconColor: AppColors.riskMedium,
            title: 'Minor Injury: Cut',
            date: 'Oct 19, 2023 - Site A',
          ),
          _buildIncidentItem(
            icon: Icons.info_outline,
            iconColor: AppColors.textLightSecondary,
            title: 'Property Damage',
            date: 'Oct 15, 2023 - Site A',
          ),
        ],
      ),
    );
  }

  Widget _buildStatCard(String label, String value, Color valueColor) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              fontSize: 14,
              color: AppColors.textLightSecondary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            value,
            style: GoogleFonts.inter(
              fontSize: 32,
              fontWeight: FontWeight.bold,
              color: valueColor,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildIncidentItem({
    required IconData icon,
    required Color iconColor,
    required String title,
    required String date,
  }) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Row(
        children: [
          Container(
            width: 44,
            height: 44,
            decoration: BoxDecoration(
              color: iconColor.withValues(alpha: 0.1),
              shape: BoxShape.circle,
            ),
            child: Icon(icon, color: iconColor, size: 24),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: GoogleFonts.inter(
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                    color: AppColors.textLightPrimary,
                  ),
                ),
                Text(
                  date,
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    color: AppColors.textLightSecondary,
                  ),
                ),
              ],
            ),
          ),
          Icon(Icons.chevron_right, color: AppColors.textLightSecondary),
        ],
      ),
    );
  }

  Widget _buildPPEComplianceTab() {
    return Center(
      child: Text(
        'PPE Compliance - Coming soon',
        style: GoogleFonts.inter(color: AppColors.textLightSecondary),
      ),
    );
  }

  Widget _buildRiskTrendTab() {
    return Center(
      child: Text(
        'Risk Trend - Coming soon',
        style: GoogleFonts.inter(color: AppColors.textLightSecondary),
      ),
    );
  }
}
